version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    allow:
      - dependency-type: development
    ignore:
      - dependency-name: "@types/node"
        update-types:
          - version-update:semver-major
          - version-update:semver-minor
    versioning-strategy: increase
    groups:
      vitest:
        patterns:
          - "vitest"
          - "@vitest/*"
      typescript-eslint:
        patterns:
          - "typescript-eslint"
          - "@typescript-eslint/*"
      eslint:
        patterns:
          - "eslint"
          - "@eslint/*"
