name: ci

on:
  push:
    branches:
      - '0.9.x'
  pull_request: {}
  workflow_call: {}

concurrency:
  group: '${{ github.workflow }} - ${{ github.head_ref || github.ref }}'
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

permissions:
  contents: read

jobs:

  check:
    strategy:
      matrix:
        node-version:
          - 18
          - 20
          - 22
          - 24

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup Yarn
        run: corepack enable

      - name: Install Packages
        run: yarn install

      - name: Type Check
        run: yarn typecheck

      - name: Lint
        run: yarn lint

      - name: Test Coverage
        run: yarn coverage

      - name: Upload Coverage
        if: ${{ matrix.node-version == 22 && github.event_name == 'pull_request' }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: coverage
          path: coverage
          retention-days: 1
