name: publish

on:
  workflow_dispatch: {}
  release:
    types:
      - published

permissions:
  contents: read

jobs:
  check:
    uses: ./.github/workflows/ci.yml

  publish:
    needs: check

    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write # Required for OIDC

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          check-latest: true
          registry-url: https://registry.npmjs.org
          package-manager-cache: false
      - name: Setup Yarn
        run: corepack enable

      - name: Install Packages
        run: yarn install

      - name: Build
        run: yarn build

      - name: Trusted Publish with Provenance
        run: npm publish
