name: report-coverage

on:
  workflow_run:
    workflows:
      - ci
    types:
      - completed

jobs:
  report:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v6

      - name: Download Coverage
        uses: actions/download-artifact@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: coverage

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@v2
        with:
          threshold-icons: "{0: '🔴', 80: '🟠', 90: '🟢'}"
