name: report-coverage

on: # zizmor: ignore[dangerous-triggers]
  workflow_run:
    workflows:
      - ci
    types:
      - completed

permissions:
  contents: read

jobs:
  report:
    if: ${{ github.event.workflow_run.event == 'pull_request' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Download Coverage
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
          name: coverage
          path: coverage

      - name: Report Coverage
        uses: davelosert/vitest-coverage-report-action@3c054a2d2e2ca45446417ad5d6d5eb33092af8f1 # v2
        with:
          threshold-icons: "{0: '🔴', 80: '🟠', 90: '🟢'}"
